defmodule Slidething.Agent do
  @moduledoc """
  Core agent types and structs for the agentic system.
  """

  defmodule AgentSpec do
    @moduledoc """
    Specification for an agent type (planner, content, layout, etc.).
    """
    defstruct [
      :name,
      :provider,
      :model,
      :temperature,
      :max_tokens,
      :max_iterations,
      :system_prompt,
      :tools
    ]

    @type t :: %__MODULE__{
            name: atom(),
            provider: String.t(),
            model: String.t(),
            temperature: float(),
            max_tokens: integer(),
            max_iterations: integer(),
            system_prompt: String.t(),
            tools: [atom()]
          }
  end

  defmodule Message do
    @moduledoc """
    LLM conversation message.
    """
    defstruct [:role, :content, :tool_calls, :tool_results]

    @type t :: %__MODULE__{
            role: :system | :user | :assistant | :tool,
            content: String.t() | nil,
            tool_calls: [ToolCall.t()] | nil,
            tool_results: [ToolResult.t()] | nil
          }
  end

  defmodule ToolCall do
    @moduledoc """
    Tool call requested by LLM.
    """
    defstruct [:call_id, :tool, :args]

    @type t :: %__MODULE__{
            call_id: String.t() | nil,
            tool: atom(),
            args: map()
          }
  end

  defmodule ToolResult do
    @moduledoc """
    Result of tool execution.
    """
    defstruct [:call_id, :tool, :success, :data, :error]

    @type t :: %__MODULE__{
            call_id: String.t() | nil,
            tool: atom(),
            success: boolean(),
            data: term() | nil,
            error: String.t() | nil
          }
  end

  defmodule RunPlan do
    @moduledoc """
    Plan generated by Planner agent.
    """
    defstruct [:intent, :tasks]

    @type t :: %__MODULE__{
            intent: String.t(),
            tasks: [SubagentTask.t()]
          }
  end

  defmodule SubagentTask do
    @moduledoc """
    Task for a subagent.
    """
    defstruct [:agent, :scope, :instruction]

    @type scope ::
            :book
            | {:page, String.t()}
            | {:pages, [String.t()]}
            | {:element, String.t()}
            | {:elements, [String.t()]}

    @type t :: %__MODULE__{
            agent: :research | :content | :layout | :media,
            scope: scope(),
            instruction: String.t()
          }
  end

  defmodule Patch do
    @moduledoc """
    Patch proposed by an agent.
    """
    defstruct [:content_changes, :layout_changes, :metadata_changes]

    @type t :: %__MODULE__{
            content_changes: [ContentChange.t()],
            layout_changes: [LayoutChange.t()],
            metadata_changes: [MetadataChange.t()]
          }
  end

  defmodule ContentChange do
    @moduledoc """
    Change to content element.
    """
    defstruct [:action, :element_id, :page_id, :element]

    @type t :: %__MODULE__{
            action: :create | :update,
            element_id: String.t() | nil,
            page_id: String.t(),
            element: map()
          }
  end

  defmodule LayoutChange do
    @moduledoc """
    Change to page layout.
    """
    defstruct [:page_id, :format_id, :element_layouts]

    @type t :: %__MODULE__{
            page_id: String.t(),
            format_id: String.t(),
            element_layouts: [ElementLayout.t()]
          }
  end

  defmodule ElementLayout do
    @moduledoc """
    Layout for a single element.
    """
    defstruct [:element_id, :bounding_box, :style]

    @type t :: %__MODULE__{
            element_id: String.t(),
            bounding_box: {{float(), float()}, {float(), float()}},
            style: map()
          }
  end

  defmodule MetadataChange do
    @moduledoc """
    Change to metadata.
    """
    defstruct [:target_id, :metadata]

    @type t :: %__MODULE__{
            target_id: String.t(),
            metadata: map()
          }
  end

  defmodule ValidationIssue do
    @moduledoc """
    Validation issue found by validators.
    """
    defstruct [:severity, :source, :target_id, :rule, :message, :measured_value, :expected_value]

    @type t :: %__MODULE__{
            severity: :error | :warning,
            source: :content | :layout,
            target_id: String.t(),
            rule: String.t(),
            message: String.t(),
            measured_value: term() | nil,
            expected_value: term() | nil
          }
  end

  defmodule RunEvent do
    @moduledoc """
    Event broadcast during a run.
    """
    defstruct [:run_id, :type, :data]

    @type t :: %__MODULE__{
            run_id: String.t(),
            type:
              :started
              | :planning
              | :executing
              | :validating
              | :repairing
              | :committed
              | :completed
              | :failed,
            data: map()
          }
  end
end
